# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Phigros\NoTopDomain\libs\feedback.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_feedbacker(object):
    def setupUi(self, feedbacker):
        feedbacker.setObjectName("feedbacker")
        feedbacker.setWindowModality(QtCore.Qt.ApplicationModal)
        feedbacker.resize(399, 318)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        feedbacker.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(feedbacker)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(feedbacker)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(feedbacker)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textEdit = QtWidgets.QTextEdit(feedbacker)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label = QtWidgets.QLabel(feedbacker)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(feedbacker)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_4 = QtWidgets.QLabel(feedbacker)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(feedbacker)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 2)
        self.label_2 = QtWidgets.QLabel(feedbacker)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 2)

        self.retranslateUi(feedbacker)
        QtCore.QMetaObject.connectSlotsByName(feedbacker)

    def retranslateUi(self, feedbacker):
        _translate = QtCore.QCoreApplication.translate
        feedbacker.setWindowTitle(_translate("feedbacker", "反馈"))
        self.pushButton_2.setText(_translate("feedbacker", "发送反馈"))
        self.label_3.setText(_translate("feedbacker", "反馈内容："))
        self.textEdit.setPlaceholderText(_translate("feedbacker", "作者建议你去github issue上提交呢...（必填）"))
        self.label.setText(_translate("feedbacker", "反馈标题"))
        self.lineEdit.setPlaceholderText(_translate("feedbacker", "必填"))
        self.label_4.setText(_translate("feedbacker", "联系方式/昵称"))
        self.lineEdit_2.setPlaceholderText(_translate("feedbacker", "选填"))
        self.label_2.setText(_translate("feedbacker", "<html><head/><body><p>PS：发送时间可能较长 <a href=\"https://github.com/LYXOfficial/NoTopDomain/issues\"><span style=\" text-decoration: underline; color:#0000ff;\">去Github提交Issue</span></a></p></body></html>"))
