# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'f:\Phigros\NoTopDomain\libs\udpattack.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UDPAttacker(object):
    def setupUi(self, UDPAttacker):
        UDPAttacker.setObjectName("UDPAttacker")
        UDPAttacker.resize(326, 424)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        UDPAttacker.setFont(font)
        self.gridLayout = QtWidgets.QGridLayout(UDPAttacker)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(UDPAttacker)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(UDPAttacker)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(UDPAttacker)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.textEdit = QtWidgets.QTextEdit(UDPAttacker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.label_3 = QtWidgets.QLabel(UDPAttacker)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.textEdit_2 = QtWidgets.QTextEdit(UDPAttacker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit_2.sizePolicy().hasHeightForWidth())
        self.textEdit_2.setSizePolicy(sizePolicy)
        self.textEdit_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.textEdit_2.setObjectName("textEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.textEdit_2)
        self.label_4 = QtWidgets.QLabel(UDPAttacker)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(UDPAttacker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.plainTextEdit.sizePolicy().hasHeightForWidth())
        self.plainTextEdit.setSizePolicy(sizePolicy)
        self.plainTextEdit.setMaximumSize(QtCore.QSize(16777215, 50))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.plainTextEdit)
        self.pushButton_2 = QtWidgets.QPushButton(UDPAttacker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(UDPAttacker)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pushButton_3)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 1)
        self.textBrowser = QtWidgets.QTextBrowser(UDPAttacker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBrowser.sizePolicy().hasHeightForWidth())
        self.textBrowser.setSizePolicy(sizePolicy)
        self.textBrowser.setMaximumSize(QtCore.QSize(16777215, 100))
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 1, 0, 1, 1)

        self.retranslateUi(UDPAttacker)
        QtCore.QMetaObject.connectSlotsByName(UDPAttacker)

    def retranslateUi(self, UDPAttacker):
        _translate = QtCore.QCoreApplication.translate
        UDPAttacker.setWindowTitle(_translate("UDPAttacker", "极域UDP重放攻击 by ht0Ruial&&modify in NTD"))
        self.pushButton.setText(_translate("UDPAttacker", "发送"))
        self.label.setText(_translate("UDPAttacker", "警告！此工具利用极域漏洞进行攻击，如使用此工具导致的任何问题作者不承担任何责任！（PS：可能出现发过一次再发就失败的bug）<span style=\"color:gray\">by ht0Ruial&&modify in NTD</span>"))
        self.label_2.setText(_translate("UDPAttacker", "对方IP（可以使用英文分号隔开）"))
        self.label_3.setText(_translate("UDPAttacker", "运行命令（CMD），留空则不发送"))
        self.label_4.setText(_translate("UDPAttacker", "发送消息内容，留空则不发送"))
        self.pushButton_2.setText(_translate("UDPAttacker", "对方关机"))
        self.pushButton_3.setText(_translate("UDPAttacker", "对方重启"))
        self.textBrowser.setMarkdown(_translate("UDPAttacker", "日志\n"
"\n"
""))
